config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"
  resources :comments, except: [:index, :show, :new]
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_closure_tree
  
  belongs_to :user
  belongs_to :parent, class_name: Comment, foreign_key: :parent_id

  validates :message, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many  :comments, dependent: :destroy

  validates :name,  presence: true
  validates :email, presence: true, email: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    @comment = current_user.comments.build(parent_id: params[:parent_id])
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      render :create
    else
      render :new
    end
  end

  def edit; end

  def update
    @comment.update_attributes(comment_params)

    if @comment.save
      render :success
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    flash[:success] = 'Your comment has been deleted.'
    redirect_to root_path
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:message, :user_id, :parent_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @root_comment         = Comment.root
    @descendant_comments  = @root_comment.children.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar(user)
    image_tag "http://secure.gravatar.com/avatar/#{Digest::MD5::hexdigest(user.email.downcase)}"
  end

  def current_user?(user)
    user == current_user
  end
end

app/views/comments/_comment.html.slim
.comments-comment-container
  ul.media-list
    li.media
      .media-left
        = link_to avatar(comment.user), 'javascript:void(0)'
      
      .media-body
        h5.media-heading = link_to "#{comment.user.name}", 'javascript:void(0)'
        p = comment.message
        p.links
          = link_to 'Reply', new_comment_path(comment), remote: true

          - if current_user?(comment.user)
            = link_to 'Edit', edit_comment_path(comment), remote: true
            = link_to 'Delete', comment, method: :delete, data: { confirm: "Are you sure?" }

        div id="reply-#{comment.id}"

        = render comment.children

app/views/comments/_form.html.slim
.comments-form-container
  = simple_form_for @comment, defaults: { label: false }, remote: true do |form|
    = form.hidden_field :parent_id
    = form.hidden_field :user_id
    = form.input :message
    = form.submit 'Submit', class: 'btn btn-primary'

app/views/comments/_popup.html.slim
div class="comments-popup-container modal fade" aria-labelledby="New address" role="dialog" tabindex="-1" rel=@comment.id
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4.modal-title Edit Comment
      .modal-body
        = simple_form_for @comment, remote: true do |form|
          = form.input :message
          = form.submit 'Submit', class: 'btn btn-primary'

app/views/comments/create.js.erb
$("#reply-<%= params[:comment][:parent_id] =%>").html('<%= j render(@comment) %>');

app/views/comments/edit.js.erb
if($('.comments-popup-container[rel=<%=@comment.id=%>]').length == 0) {
  $('body').append("<%= j render partial: 'popup' %>");
}

<% if @comment.errors.any? %>
  $('.comments-popup-container[rel=<%=@comment.id=%>]').remove();
  $('body').append("<%= j render partial: 'popup' %>");
<% end %>

$('.comments-popup-container[rel=<%=@comment.id=%>]').modal('show');

app/views/comments/new.js.erb
$("#reply-<%= params[:parent_id] =%>").html('<%= j render('form') %>');

app/views/comments/success.js.erb
location.reload();

app/views/home/index.html.slim
#home-index-container
  .container
    .row
      .col-md-12
        h1 Comments
        
        = render @root_comment

app/views/layouts/application.html.slim
doctype html
html
head
  title Rails Test 9
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

body
  - flash.each do |name, msg|
    = content_tag :div, msg, class: "alert alert-#{name}"
    
  = yield
  